version: '3.8'

services:
  nacos:
    image: nacos/nacos-server:v2.4.3
    container_name: nacos
    environment:
      - MODE=standalone
      - IP_ADDRS=host.docker.internal
    ports:
      - "8848:8848"
      - "9848:9848"
    restart: unless-stopped

  sentinel:
    image: bladex/sentinel-dashboard:1.8.8
    container_name: sentinel
    ports:
      - "8858:8858"
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom
      - SERVER_PORT=8858
    restart: unless-stopped

  seata:
    image: seataio/seata-server:2.0.0
    container_name: seata
    environment:
      - registry.type=file
      - config.name=file
      - host.docker.internal=host.docker.internal
    ports:
      - "8091:8091"
    restart: unless-stopped