server:
  port: 15000

spring:
  application:
    name: spring-ai

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.xty.app
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:1.5b
          temperature: 0.7