server:
  port: 9000

spring:
  application:
    name: service-product

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
      discovery:
        namespace: dev

    sentinel:
      transport:
        dashboard: localhost:8858
      eager: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379